module.exports =
{
    REQUEST_BUTTON_SETTINGS: "REQUEST_BUTTON_SETTINGS",
    DELIVER_BUTTON_SETTINGS: "DELIVER_BUTTON_SETTINGS",
    BUTTON_PRESSED: "BUTTON_PRESSED",
    BUTTONS_UPDATE: "BUTTONS_UPDATE"
};