module.exports = {
  BOARD_WEBSERVER_DEFAULT_PORT: process.env.BOARD_WEBSERVER_DEFAULT_PORT || '8097',
  BOARD_WIDTH: process.env.BOARD_WIDTH || '800',
  BOARD_HEIGHT: process.env.BOARD_HEIGHT || '480',
  BOARD_ROWS: process.env.BOARD_ROWS || 3,
  BOARD_COLUMNS: process.env.BOARD_COLUMNS || 8,
  PIXEL_PER_MM_WIDTH: process.env.PIXEL_PER_MM_WIDTH || 7.4074074074,
  PIXEL_PER_MM_HEIGHT: process.env.PIXEL_PER_MM_HEIGHT || 7.5,
  BUTTON_WIDTH: process.env.BUTTON_WIDTH || 20,
  BUTTON_HEIGHT: process.env.BUTTON_HEIGHT || 20,
  BUTTON_GAP_WIDTH: process.env.BUTTON_GAP_WIDTH || 2,
  BUTTON_GAP_HEIGHT: process.env.BUTTON_GAP_HEIGHT || 2
}